baseURL = "https://zarguell.github.io/recipes-as-code/"  # Will be overridden by workflow
languageCode = "en-us"
title = "Recipe Collection"
theme = "cookbook" 

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
