baseURL = "https://zarguell.github.io/recipes-as-code/"
languageCode = "en-us"
title = "Recipe Collection"
theme = "cookbook"

canonifyURLs = true
relativeURLs = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
